[package]
name = "loa-gatekeep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

meter-core = { path = "C:\\Users\\jonas\\Documents\\github\\meter-core-rs\\" }